language: python
sudo: false
python:
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  nosetests --verbose --with-coverage --cover-package=machikoro tests
after_success:
  coveralls
